serial:
  port: "/dev/ttyACM0"
  baudrate: 921600

motors:
  - addr: 1
    name: "motor_1"
    speed_rpm: 1000
    accel: 200

  - addr: 2
    name: "motor_2"
    speed_rpm: 1000
    accel: 200

  - addr: 3
    name: "motor_3"
    speed_rpm: 1000
    accel: 200

